---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##   
  ## Added operator rules for Cluster Resource Quota
  ##   
  - apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - user.openshift.io
    resources:
      - users
    verbs:
      - get
      - list
      - watch
  ##
  ## Rules for tiering.redhat.com/v1, Kind: Tier
  ##
  - apiGroups:
      - tiering.redhat.com
    resources:
      - tiers
      - tiers/status
      - tiers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
