# permissions for end users to edit tiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tier-editor-role
rules:
- apiGroups:
  - tiering.redhat.com
  resources:
  - tiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tiering.redhat.com
  resources:
  - tiers/status
  verbs:
  - get
