# permissions for end users to view tiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tier-viewer-role
rules:
- apiGroups:
  - tiering.redhat.com
  resources:
  - tiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tiering.redhat.com
  resources:
  - tiers/status
  verbs:
  - get
